# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: http://of0mq0cfg.bkt.clouddn.com/images/logo.png
bio: 'A designer, developer and entrepreneur. Spends his time travelling the world with a bag of kites. Likes journalism and publishing platforms.'

# Content
excerpt_link: Read More

# Miscellaneous
rss:
